# Generated by Django 5.2.1 on 2025-06-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_image_profile_profile_pic_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
